spring.application.name=file-service
server.port=9002
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

cloudflare.r2.access-key=${CLOUDFLARE_R2_ACCESS_KEY}
cloudflare.r2.secret-key=${CLOUDFLARE_R2_SECRET_KEY}
cloudflare.r2.bucket=${BUCKET_NAME}
cloudflare.r2.endpoint=https://${CLOUDFLARE_R2_ACCOUNT_ID}.r2.cloudflarestorage.com


