server.port=9005
spring.application.name=notification-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:postgresql://localhost:5432/notificationservice
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.auto-commit=false

# JWT matching other services for token validation if needed
jwt.base64-secret=WXw+FVujWxS1YAhmQt0W5FiId7LvI4IRfqPUG7rNhVdBya2PfiFa93EAw7Q06qB5cNKSrzjF2JTtzAB91kC1mA==

application.custom.authservice=/service-api/v1/users
