# Server Config
server.port=9001

# Eureka Client Config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Spring Application Config
spring.application.name=core-service
spring.cloud.discovery.enabled=true

# Datasource Config
spring.datasource.url=jdbc:postgresql://localhost:5432/coreservice
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA & Hibernate Config
spring.jpa.properties.hibernate.default_schema=core
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Flyway Migration Config
#spring.flyway.enabled=true
#spring.flyway.schemas=core
#spring.flyway.baseline-on-migrate=true
#spring.flyway.locations=classpath:db/migration

# Virtual Threads Config (Java 21)
#spring.threads.virtual.enabled=true